"""empty message

Revision ID: cf770c39844c
Revises: 
Create Date: 2019-11-17 22:46:17.832654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf770c39844c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['hospital.address'], ),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('doctor',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('doc_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['hospital.address'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('hospital',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('medication',
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('med_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.report_id'], ),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('patient',
    sa.Column('ssn', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('dob', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ssn')
    )
    op.create_table('report',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('ssn', sa.String(), nullable=True),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('med_id', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('patient_info', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['doctor.doc_id'], ),
    sa.ForeignKeyConstraint(['med_id'], ['medication.med_id'], ),
    sa.ForeignKeyConstraint(['ssn'], ['patient.ssn'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('patient')
    op.drop_table('medication')
    op.drop_table('hospital')
    op.drop_table('doctor')
    op.drop_table('department')
    # ### end Alembic commands ###
